spring:
  cloud:
    config:
      profile: prod
  profiles:
    active: prod
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@eureka-server:8762/eureka/
security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
