#spring:
#  cloud:
#    config:
#      profile: prod
#  profiles:
#    active: prod
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  config:
    stream:
      maxConcurrentConnections: 50

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
    metadata-map:
      cluster: main
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@eureka-server:8762/eureka/
security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
management:
  security:
    enabled: false
