server:
  port: 8040

turbine:
  stream:
    port: 8041

spring:
  rabbitmq:
    host: rabbitmq
#    port: 15672
#    username: guest
#    password: guest
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
#      turbine:
#        clusters: default
#        location: http://monitor-server:${turbine.stream.port}
turbine:
  app-config: demo-server,gateway-server   ##需要监控的服务名
  aggregator:
    clusterConfig: main ##需要监控的服务集群名
  clusterNameExpression: metadata['cluster']
